for debugging scroll-behavior
mate-academy/layout_landing-page pull request #1116
Opened 2024-02-11 19:49 UTC by danil-maksimenko

2024-02-11 20:03 UTC, VitaliyBondarenko1982 requested changes
Waiting other sections

Smooth scroll working correctly

![chrome-capture-2024-2-11 (2)](https://github.com/mate-academy/layout_landing-page/assets/33029864/4ffafff6-3c5d-4a94-9505-39d0036a5864)

2024-02-27 12:13 UTC, anastasiiavorobiova requested changes
Make sure to deploy your page

2024-02-27 12:13 UTC, anastasiiavorobiova commented on README.md
> +- Deploy and create a Pull Request with a [DEMO LINK](https://danil-maksimenko.github.io/layout_landing-page/)
Add this link to the PR description

2024-02-27 14:09 UTC, anastasiiavorobiova requested changes
Try to redeploy your page 
<img width="620" alt="Screenshot 2024-02-27 at 16 09 27" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/852cb5b8-c84f-47a4-81e3-4024cd28fa63">

2024-02-27 14:36 UTC, anastasiiavorobiova requested changes
Great work! 
<img width="355" alt="Screenshot 2024-02-27 at 16 35 07" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/fba06dcf-b8c8-4c9d-9826-ac6a6b635a94">
Consider adding hover styles here 
<img width="119" alt="Screenshot 2024-02-27 at 16 34 36" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/e50259a0-38b7-4d54-88ca-c5d117869d1a">
Consider showing the phone number on the hover

2024-02-27 17:55 UTC, vadiimvooo requested changes
Good job. A few changes required:
1. You need to fix scale of the elements. They should not overlap neighbor elements.
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/6eaa9ab0-f07a-4894-902e-1b786a928d0c)
2. Remove scroll when burger menu is opened.
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/09dc5c89-3f7a-4b31-bd24-92326a8e5d6a)

2024-02-27 18:53 UTC, maxim2310 requested changes
Great job overall! Just one tiny thing needs to be fixed before approval)

also block must not overlap 
![image](https://github.com/mate-academy/layout_landing-page/assets/96265844/014ac108-9f3e-4bd7-84cd-dae2949a8b56)

2024-02-27 19:56 UTC, vadiimvooo approved these changes
LGTM

2024-07-12 09:21 UTC, closed without merging