develop
mate-academy/layout_landing-page pull request #1322
Opened 2024-04-26 11:14 UTC by rekverr

- Deploy and create a Pull Request with a [DEMO LINK](https://rekverr.github.io/layout_landing-page/)

2024-04-26 12:32 UTC, SanyaBratashchuk requested changes
1. disable scroll when menu is open 
![image](https://github.com/mate-academy/layout_landing-page/assets/97547824/42057f40-081a-423e-9abf-829af143c402)
2. should be links 
![image](https://github.com/mate-academy/layout_landing-page/assets/97547824/98f98b99-cc45-4636-b442-23ade169e754)
3. get rid of horizontal scroll

2024-04-28 16:18 UTC, vadiimvooo requested changes
Almost done. Just fix all prev comments.
`should be links`
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/33eba26c-7fab-49b6-b466-c50f1ecabb54)
2. Broken styles on tablet
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/5ce47e7a-cde5-46af-b7c6-feabb0a4ebb0)

2024-04-28 16:41 UTC, vadiimvooo requested changes
Links still not added. Here are some useful links
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers
This link should move to google maps for appropriate address.
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/7e368ca6-a1bf-4ee7-a437-ccfb231d4149)
Please feel free to ask for help in fe_chat if you have any questions.

2024-04-28 16:58 UTC, vadiimvooo approved these changes
Well done!)

2026-02-23 22:29 UTC, closed without merging