Develop
mate-academy/layout_landing-page pull request #1364
Opened 2024-05-15 18:55 UTC by ikocherovets

- [MET landing](https://www.figma.com/file/lSR1m42L9YwzQwzzxKwHpw/THE-MET)
- [DEMO LINK](https://ikocherovets.github.io/layout_landing-page/)
this is not the latest version, lots of corrects will be done.

2024-05-16 11:11 UTC, closed without merging

2024-05-17 04:56 UTC, roman-mirzoian requested changes
Good start, see work in progress. 
There is a two moments that you can fix with alignment:

and you also need to fix the page when the menu is open (when the menu is open, you can scroll below with the mouse wheel, the effect of which you see on the gif)

https://gyazo.com/9e999f8aace82efcd200827565dc5f26

2024-05-20 09:05 UTC, ikocherovets commented
here is almost done version of my landing page, I will come back with that after some time, need to focus on JS Advanced (Alisa told us to do that)

2024-05-20 12:55 UTC, roman-mirzoian requested changes
I didn't see any changes in the demo, maybe you accidentally forgot to update deployment.

2024-05-20 21:39 UTC, ikocherovets commented
@roman-mirzoian take my apologies, I totally forgot about that part of actions. Here is updated demo link to my landing page after `npm run deploy` command.

2024-05-21 09:31 UTC, roman-mirzoian requested changes
Good work, I can see progress in completing the task. But there is still work to be done.

Let's go through the [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md).

1) Use the logo as a favicon.
2) Use the landing name as a page title
example: `Logo` THE MET

![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/8179899b-1812-47a0-aee5-2761686fd542)

3) All logos should be links to the top of the page
(these pictures do not have a link to the top of the page)
![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/5e0786aa-ce21-4650-af0e-96bcb2e4afcb)

it is also better to add a small hover size for all pictures.

4) phone numbers, emails and links to maps must be clickable with a hover effect
![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/f8773a72-e355-43f4-95dc-511a3ad0d676)

![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/c04c10f6-8bfb-4e69-84a0-74f24e0c824c)
https://gyazo.com/d67b011bba2e85470fc46d390bf9cc91

![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/06f84b0c-bf05-47a3-a157-361e81cee834)
https://gyazo.com/5824b28dffe686283dd7fb01741ccc09

although you need to add an image below
![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/9183c819-22b3-45e4-8c9e-1eb0b2dd332c)

2024-05-21 22:51 UTC, ikocherovets commented
Hello dear mentors :)
Here is my landing page, I need to make the last corrects, specifically convert magic numbers to variables. In order to not waste time, I push my landing code for your review :)
[DEMO LINK](https://ikocherovets.github.io/layout_landing-page/)

2024-05-22 08:13 UTC, roman-mirzoian requested changes
Good job, I see you have corrected most of my comments, there is still a bit to correct.

1) It is better to add a small hover size effect to these pictures.
https://gyazo.com/656b5c26d5df887cc6bc1f334d6f2921

2) Also necessary to add a hover to the links of email numbers and geolocations and to the buttons:
![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/a072d816-0063-4e8a-aaa2-3dd4c6e200b0)
  https://gyazo.com/b784c6e2c630894cd3ad3b8c8f27522c

![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/e0ebf3c0-707f-407e-a7b3-206d7fc2b392)

3) At a width of 320 pixels, the display, background of the header and footer is broken
  https://gyazo.com/5914bd65d6ae2fd7a6ea97e007ffe76b

2024-05-22 08:13 UTC, roman-mirzoian commented on src/blocks/reasons.scss
> +    font-weight: 400;
```suggestion
```

2024-05-22 08:13 UTC, roman-mirzoian commented on src/blocks/section-title.scss
> +    font-weight: 400;
```suggestion
```

2024-05-23 09:24 UTC, roman-mirzoian requested changes
Well done, but pay attention to these comments:
1) Here you need to change the color, not the size
https://gyazo.com/a1199039fb955809463b05db565b22ee
![image](https://github.com/mate-academy/layout_landing-page/assets/54860641/de3bc1ac-1548-447c-bcac-c86aadcbf4b6)

2) This guidance looks sharp and uneven, it is better to increase the size, for example, by 5 - 10% with a smooth transition
https://gyazo.com/4785b249d2610453ff12c3aa574612f6

3) There is also a small bug with the footer that can be easily fixed
https://gyazo.com/388d984180eb5825ea6b82e6b5697815

2024-05-23 10:26 UTC, ikocherovets commented
Hi, Roman :) Thanks for the patience with all these comments which you've been giving to me. I know it can be annoying, but it's only because of them, I'm getting better.

2024-05-23 10:47 UTC, roman-mirzoian approved these changes
Well done, I see the correct edits in the code. I also see that you updated the deploy a few minutes ago, but for some reason it was not updated.

https://gyazo.com/ab90a2464298bbc2ef0718d84e48efa6

Don't worry and keep up the good work, you're doing great.