landing page
mate-academy/layout_landing-page pull request #1427
Opened 2024-06-19 17:39 UTC by anna-agerone

# Landing page

Name of the project: MYBIKE Landing

My page: [DEMO LINK](https://anna-agerone.github.io/layout_landing-page/)

Design: - [MYBIKE landing](https://www.figma.com/file/NZQAIydtHo5QkINyGLHNcq/BIKE-New-Version?node-id=0%3A1)

2024-06-19 18:05 UTC, TarasHoliuk commented
1. No need to scale the entire header on hover (image here is only the background)

2. Phone number should appear on hover:

![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/d7ff4b3b-1bc0-4ada-98d6-6fb09293037a)

Design:

![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/60af0480-7854-4a35-9586-bced4e96499b)

3. Would be nice to add hover effect here (in addition to cursor: pointer):

![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/e87cc0d7-e761-4ead-9808-b8c6674bb65a)

4. Because of adding a border on hover content below is "jumping". Instead, change styles for outline (not remove but change color). Or add border by default with transparent color, and change color on hover

![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/53b83ccd-ccf7-40bc-a8fd-19c0c63538db)

5. Remove white space in the footer:

![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/9493a6a5-b6c7-47df-9824-67759c0ed14d)

2024-06-19 18:05 UTC, TarasHoliuk requested changes
Nicely done 👍 

Let's add a few improvements

2024-06-19 22:47 UTC, anna-agerone commented
> Nicely done 👍
> 
> Let's add a few improvements

Fixed

2024-06-20 08:17 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your page:
1. Add transition for hover effects everywhere 
<img width="588" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/2bcadd87-686c-458a-a7da-03a9c0339b5e">

2. Fix the border radius and height for the inputs, check it on the design 
<img width="730" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/07edcb6b-7f1f-463b-96e8-b4195a5d5dbc">

3. You need to change autofill styles for the form fields
https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ 
<img width="762" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/5528d57a-c4e5-470d-867d-d85948a0726d">

4. You need to hide the phone number on the mobile and tablet versions 
<img width="563" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/94c30044-b708-4314-b163-c79200435e38">

2024-06-20 16:11 UTC, TarasHoliuk approved these changes
Looks good to me 👍 Approved ✔️

2025-02-08 18:01 UTC, closed without merging