header and aside menu
mate-academy/layout_landing-page pull request #18
Opened 2023-05-28 16:54 UTC by olhry

[DEMO LINK](https://olhry.github.io/layout_landing/

2023-05-29 06:45 UTC, OleziO requested changes
Fix demo link

2023-05-29 10:40 UTC, olhry commented
> Виправити демо-посилання

Fixed demo

2023-05-29 11:17 UTC, demetrxx requested changes
There are no sections, except the hero. Where are the others? 
Considering the available result, the following checklist requirements should be satisfied:
4 - Change text color on hover for phone, email and address
7 - Increase all images on hover 
9 - The speed of animations should be the same throughout the page
10 - Ensure that all nav__links work smoothly

2023-07-17 21:04 UTC, olhry commented
Made header and aside mune full

2023-07-18 07:57 UTC, polosanya requested changes
Keep up the good work!
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/cd107892-769d-45cf-8140-9e4094237c68)
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/6f36fdef-c3f0-4232-8085-35f08bfff651)
2. There is something wrong with the hover effect. Pay attention to the phone icon
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/09476640-f5e7-440a-9770-507b4f5b50ab)

2023-07-18 17:49 UTC, loralevitska requested changes
Keep up the good work! Re-request next review after finish whole landing

2023-08-31 07:45 UTC, DarkMistyRoom requested changes
Good job! Check the comments:
- add hover effects to all images
- apply transition to the button's hover effect
<img width="421" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/98764641/efc989be-9e0f-47ee-b6b6-5166d385b4e9">

- the contacts should be links
<img width="553" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/98764641/eaed09da-c700-45d7-a407-ec00f086aecb">

- don't navigate to the header on form submitting. Make all form fields required and reset the form upon submitting
- the is too much side space. Should be 72px on each side (tab)
<img width="1245" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/98764641/17e2cfe4-c5b8-4771-8069-51f1e029b408">

<img width="1245" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/98764641/3f4cfb66-5681-4a65-8a77-2db1378fb51f">

- these images look bigger on the mockup (tab)
<img width="622" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/98764641/775de4f9-57b2-4b21-908b-e3f5e9921f6b">

- add scroll to the menu to make it work fine in landscape mode
<img width="746" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/98764641/50a678b2-5cee-47d3-96a1-26093c806268">

2023-09-02 15:49 UTC, olhry commented
Звіт: 
> * додати ефекти наведення курсора на всі зображення 
Зробив збільшення +20% при наведенні, але мені не дуже подобається. 
> * застосувати перехід до ефекту наведення кнопки.
При наведенні ховер працює як на макеті. 
> 
> <img alt="зображення" width="421" src="https://user-images.githubusercontent.com/98764641/264571467-efc989be-9e0f-47ee-b6b6-5166d385b4e9.png">
> * контакти мають бути посиланнями
Телефони та адреси зробив посланнями
> <img alt="зображення" width="553" src="https://user-images.githubusercontent.com/98764641/264571627-eaed09da-c700-45d7-a407-ec00f086aecb.png">
> * не переходьте до заголовка під час надсилання форми. Зробіть усі поля форми обов’язковими та скиньте форму після надсилання
При наведенні ховер працює як на макеті. Кнопку посилання замінив на кнопку відправлення інфо. 
Як зробити скидання форми?
> * занадто багато бічного простору. Має бути 72 пікселя з кожного боку (вкладка)
> 
> <img alt="зображення" width="1245" src="https://user-images.githubusercontent.com/98764641/264572187-17e2cfe4-c5b8-4771-8069-51f1e029b408.png"> <img alt="зображення" width="1245" src="https://user-images.githubusercontent.com/98764641/264572177-3f4cfb66-5681-4a65-8a77-2db1378fb51f.png">
> * ці зображення виглядають більшими на макеті (вкладка)
виправив
>
> * додайте прокручування до меню, щоб воно добре працювало в ландшафтному режимі
зробив скрол авто

2023-09-03 20:15 UTC, witflash requested changes
You're almost done!

1. To reset your form without opening 404 page you can use this simple attribute for your form:
```
<form
  onsubmit="this.reset(); return false;"
```

2. It may make sense to decrease image size on hover. Because it covers nearest text and other images:
![image](https://github.com/mate-academy/layout_landing-page/assets/25587299/37612975-5c0e-43ab-9724-783e59f248f9)

2023-09-03 20:33 UTC, olhry commented
вніс запропоновані зміни

2023-09-04 08:59 UTC, anastasiia-tilikina approved these changes
GJ!

2024-04-05 21:30 UTC, closed without merging