First commit
mate-academy/layout_landing-page pull request #1826
Opened 2024-11-22 00:14 UTC by MannyShussan

- Deploy and create a Pull Request with a [DEMO LINK](https://MannyShussan.github.io/layout_landing-page/)

2024-11-22 15:11 UTC, joaorpereira requested changes
1. convert all images and icons files to lowercase, this is causing issues when you type the files to be imported
2. verify all paths where you are importing the images, a lot of paths are incorrect. use ctrl + click on the path to verify if the path is valid or not

2024-11-22 15:27 UTC, joaorpereira commented on src/styles/style.css.map
> +{"version":3,"sourceRoot":"","sources":["style.scss","../utils/mixins.scss","blocks/contacts-block.scss","../utils/variables.scss","blocks/button.scss","blocks/form.scss","blocks/about-us.scss","bloc
why this file is generated? delete this file, letś just use scss

2024-11-22 15:27 UTC, joaorpereira commented on src/styles/style.css
> +.container {
why this file is generated? delete this file, letś just use scss

2024-11-22 15:27 UTC, joaorpereira commented on src/index.html
> +      href="./styles/style.scss"
`  href="./styles/main.scss"`

2024-11-22 15:27 UTC, joaorpereira commented on src/styles/style.scss
> +/* stylelint-disable import-notation */
move this content to `main.scss` file an delete the file style.scss


```
@import '../utils/variables.scss';
@import '../utils/mixins.scss';
@import './blocks/contacts-block';
@import './blocks/button';
@import './blocks/form';
@import './blocks/about-us';
@import './blocks/categories';
@import './blocks/recommended';
@import './blocks/product';
@import './blocks/main';
@import './blocks/section-title';
@import './blocks/page';
@import './blocks/header';
@import './blocks/top-bar';
@import './blocks/icon';
@import './blocks/menu';
@import './blocks/nav';
```

2024-11-22 15:27 UTC, joaorpereira commented on src/styles/blocks/icon.scss
> +    background-image: url(../images/icons/Icon-Phone-Call.svg);
`background-image: url(../images/icons/Icon-Phone-call.svg);`

2024-11-23 14:40 UTC, julianFBarbosa commented
Demo link is not available
![image](https://github.com/user-attachments/assets/dde1befd-8eca-4361-879f-2c717271e5a5)

2024-11-25 13:34 UTC, joaorpereira commented on src/styles/blocks/icon.scss
> +    background-image: url(../images/icons/icon-burger-menu.svg);
**Inconsistent Case in File Names:**

CSS URLs are case-sensitive. For example:
icon-burger-menu.svg is lowercase, while later you reference Icon-Burger-menu.svg with mixed case. If your actual file names don't match this case exactly, the images won't load.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

2024-11-25 13:34 UTC, joaorpereira commented on src/styles/blocks/icon.scss
> +      background-image: url(../images/icons/icon-burger-menu-hover.svg);
**Inconsistent Case in File Names:**

CSS URLs are case-sensitive. For example:
icon-burger-menu.svg is lowercase, while later you reference Icon-Burger-menu.svg with mixed case. If your actual file names don't match this case exactly, the images won't load.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

2024-11-25 13:34 UTC, joaorpereira commented on src/styles/blocks/icon.scss
> +    background-image: url(../images/icons/icon-close.svg);
**Inconsistent Case in File Names:**

CSS URLs are case-sensitive. For example:
icon-burger-menu.svg is lowercase, while later you reference Icon-Burger-menu.svg with mixed case. If your actual file names don't match this case exactly, the images won't load.

https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

2024-11-25 13:35 UTC, joaorpereira commented on src/styles/blocks/icon.scss
> +}
```
.icon {
  display: block;
  height: 24px;
  width: 24px;
  background-image: url("../images/icons/Icon-Burger-menu.svg");
  background-size: cover;
  transition: transform $effectDuration;

  @include hover(transform, scale(1.2));

  @include on-tablet {
    height: 32px;
    width: 32px;
  }

  &--phone {
    background-image: url("../images/icons/Icon-Phone-call.svg");
  }

  &--menu {
    background-image: url("../images/icons/Icon-Burger-menu.svg");

    &:hover {
      transform: scale(1.2);
      background-image: url("../images/icons/Icon-Burger-menu-hover.svg");
    }
  }

  &--close {
    background-image: url("../images/icons/Icon-Close.svg");
  }
}

```

2024-11-25 14:04 UTC, joaorpereira commented
@MannyShussan please be sure to run: `npm run deploy`

to verify your code errors you can also run: `npm run deploy -- -l`

error:

![78606dfd-f820-4262-878e-db5aff47ee7e (1)](https://github.com/user-attachments/assets/aea4a9bf-97f2-4d7b-9da0-a2e072e0e4aa)

2024-11-26 23:44 UTC, raulriato requested changes
Hey, @MannyShussan, can you confirm if you ran the command `npm run deploy`? If you do not run it, we aren't able to review your application. Make sure to run it, and if you have any troubles, call for help in the chat :)

2024-11-27 09:17 UTC, MannyShussan commented
I remember having run command

2024-11-27 09:26 UTC, MannyShussan commented
I ran again. Done! check again

2024-11-27 18:21 UTC, julianFBarbosa commented on src/index.html
> +            <form
Form validation isn't working properly.


https://github.com/user-attachments/assets/834a768c-40b0-46e5-bd3e-0147f3228b9c

2024-11-27 18:21 UTC, julianFBarbosa commented on src/index.html
> +            <div class="about-us__news">
the `about` section has the same background as the `contact-us`, this isn't a explicit requirement on the checklist but it gives a weird appearance on the website.

![image](https://github.com/user-attachments/assets/c78b0cc0-8389-45d1-ba7a-5cb2b670ed7b)


on Figma this section looks like this:

![image](https://github.com/user-attachments/assets/afe8694d-2778-47d6-ae00-2700146b65a3)

2024-11-27 18:21 UTC, julianFBarbosa commented on src/index.html
> +    <aside
This gray background does not exist on Figma, giving an strange look to the menu.

![image](https://github.com/user-attachments/assets/cca16bba-e8dc-4fba-ad78-6bb1df519557)


on Figma:

![image](https://github.com/user-attachments/assets/1a1fd185-8007-4b1f-ad0c-fbd6126a1d0b)

2024-11-27 18:21 UTC, julianFBarbosa commented on src/index.html
> +            <h2 class="section-title section-title--contact-us">contact-us</h2>
I think that you forgot to change the title from `contact-us` to `Contact Us`

2024-11-29 02:53 UTC, MannyShussan commented
I made some changes, check it out

2024-11-29 17:38 UTC, joaorpereira requested changes

2024-11-29 17:38 UTC, joaorpereira commented on src/index.html
> +                <button class="button">
this button is not styled well

verify outline property of the button

the ui of button "send" is correct

2024-11-29 17:38 UTC, joaorpereira commented on src/index.html
> +              class="product recommended__product"
the correct color of text is not blue

2024-11-29 17:38 UTC, joaorpereira commented on src/index.html
> +              class="product recommended__product"
the correct color of text is not blue

2024-11-29 17:38 UTC, joaorpereira commented on src/index.html
> +              class="product recommended__product"
the correct color of text is not blue

2024-11-29 17:38 UTC, joaorpereira commented on src/index.html
> +          <div class="about-us__banner"></div>
this banner should fill the hole width of the page. right now it respected the padding of the page. you should remove this section from the section that contain the padding logic and after this section add back this padding value

2024-12-02 14:40 UTC, closed without merging