MyBike landing page
mate-academy/layout_landing-page pull request #1861
Opened 2024-12-06 18:56 UTC by FelixTheFallen

[DEMO LINK](https://FelixTheFallen.github.io/layout_landing-page/)

2024-12-07 08:44 UTC, anastasiiavorobiova requested changes
Make sure to deploy your solution

2024-12-07 12:12 UTC, FelixTheFallen commented
Uh sorry for a question but how to deploy work?

2024-12-09 14:54 UTC, FelixTheFallen commented
src/index.html
[error] src/index.html: SyntaxError: Opening tag "link" not terminated. (11:5)
[error]    9 |     <link rel="preconnect" href="https://fonts.gstatic.com">
[error]   10 |     <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">
[error] > 11 |     <link rel="stylesheet" href="styles/block/main.scss"
[error]      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error] > 12 |     <script src="scripts/main.js" defer></script>
[error]      | ^^^^^
[error]   13 |   </head>
[error]   14 |   <body class="page__body">
[error]   15 |     <header class="header">

and what this error means?

2024-12-10 07:44 UTC, volodymyr-soltys97 requested changes
Hi, the demo link isn't working, you need to make a deploy and check it after on the demo link 
<img width="745" alt="image" src="https://github.com/user-attachments/assets/ff0b963e-038a-43ce-b482-8abed208236a">

2024-12-10 07:44 UTC, volodymyr-soltys97 commented on src/index.html
> +    <link rel="stylesheet" href="styles/block/main.scss"
```suggestion
    <link rel="stylesheet" href="styles/block/main.scss">
```

2024-12-10 17:28 UTC, closed without merging