cr layout only
mate-academy/layout_landing-page pull request #235
Opened 2023-06-26 13:52 UTC by OPTIMISTIXX

[DEMO LINK](https://OPTIMISTIXX.github.io/layout_landing-page/)

2023-06-26 16:09 UTC, anastasiiavorobiova commented on src/index.html
Use an HTML validator such as https://validator.w3.org/nu/#textarea to validate your HTML, there are some errors here

2023-07-04 15:07 UTC, mykhalenych requested changes
add phone number with hover and add hover for menu icon

<img width="213" alt="Screenshot 2023-07-04 at 17 50 16" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/6c211770-f32f-4530-85cc-8184a9c71bcd">

phone and email must be links

<img width="335" alt="Screenshot 2023-07-04 at 17 54 16" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/59013487-f81d-450a-ade3-6b9e7a0258e1">

delete autocomplete styles

<img width="570" alt="Screenshot 2023-07-04 at 17 54 57" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/e9f3ea39-2d24-4770-bdbb-af59c4079d94">

add hover to all links

<img width="376" alt="Screenshot 2023-07-04 at 17 55 08" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/6e386f08-fb28-48ed-89ce-9da2f0231fb7">


and increase width for image

<img width="328" alt="Screenshot 2023-07-04 at 18 07 15" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/58265f0f-1794-45f5-811e-4c662753d33a">


fix this issue

<img width="571" alt="Screenshot 2023-07-04 at 17 57 15" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/4e4296bf-4067-4cd0-b00d-bb062e4c3fed">

2023-07-05 11:55 UTC, anastasiiavorobiova requested changes
Great work! Added comments to fix: 
<img width="641" alt="Screenshot 2023-07-05 at 14 44 52" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/3abc5825-99f5-4b4f-a009-df6ab1c26c3b">
Consider validating your HTML via HTML validator, there are some errors here
<img width="335" alt="Screenshot 2023-07-05 at 14 45 29" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/ec2753f6-a699-4181-b1a2-a387f4dfdf3c">
Consider using a better-quality image for the logo. Now it's a bit blurry
<img width="245" alt="Screenshot 2023-07-05 at 14 46 12" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/7ffbba2d-3afe-4c11-ae20-5ebb61db15c6">
<img width="182" alt="Screenshot 2023-07-05 at 14 46 16" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/5880f78c-cdd2-4cef-9e63-fffb6842e248">
Consider using the same styling for links
<img width="302" alt="Screenshot 2023-07-05 at 14 47 27" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/4a5b6dbb-dc3c-44c8-9f13-ff13bf32277e">
Two links don't work in the footer
<img width="844" alt="Screenshot 2023-07-05 at 14 49 42" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/3d2872b4-01c6-4b5b-baea-e2747affceae">
Consider adding bottom padding for the footer
<img width="775" alt="Screenshot 2023-07-05 at 14 50 01" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/c7ccb22d-782d-4c7b-afb6-3a6f883bd72e">
The menu for mobiles in landscape mode isn't scrollable

2023-07-05 18:01 UTC, TarasHoliuk requested changes
Everything looks good to me except for 1 thing - no favicon
Let's add it to make your landing page more natural (you will add it to the portfolio)

2023-07-06 09:46 UTC, volodymyr-soltys97 requested changes
Add `cursor: pointer` for this button and remove border
<img width="619" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/d6692d53-785d-43de-8f56-c33209faf70d">

Add transition for changing background size when hovering
<img width="1134" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/5fe29ddd-0e96-4f0e-9f5c-4e8e19aa46eb">

2023-07-06 11:36 UTC, volodymyr-soltys97 requested changes
Still not fixed from previous review
<img width="889" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/58fe5be5-7f08-4221-9500-180b12aadca2">

2023-07-06 13:11 UTC, mykhalenych requested changes
change autocomplete styles
<img width="599" alt="Screenshot 2023-07-06 at 16 10 27" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/c246242c-3312-4f07-98d9-2ac3a6ee69aa">

it must be link
<img width="269" alt="Screenshot 2023-07-06 at 16 10 30" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/1321790b-7057-43e3-80b3-424ed8aad827">

add phone number with hover
<img width="229" alt="Screenshot 2023-07-06 at 16 10 35" src="https://github.com/mate-academy/layout_landing-page/assets/53228259/88720a7f-8697-4354-a00a-8b6ef12261ab">

2023-07-06 14:03 UTC, anastasiiavorobiova requested changes
Great work! Let's make it perfect:
<img width="334" alt="Screenshot 2023-07-06 at 15 56 58" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/c0395362-d323-4399-a569-79a327f69a10">
These should be links with ability to mail to the company or a call to the company on click
<img width="1241" alt="Screenshot 2023-07-06 at 15 56 01" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/2e8f398e-506b-4474-bf38-a40ef744026e">
Consider adding more space between the button and the end of the page
<img width="533" alt="Screenshot 2023-07-06 at 15 55 22" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/25fbafe3-8841-4451-ad4c-272e0f9ed621">
The image hides the content on hover, consider fixing it
<img width="173" alt="Screenshot 2023-07-06 at 15 54 48" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/2b6c8ca7-fb3f-488e-a30c-53e4e1eb92b7">
Consider adding the block with the phone number on the hover

2023-07-06 17:59 UTC, anastasiiavorobiova requested changes
Awesome landing! Consider fixing this overlap 
<img width="258" alt="Screenshot 2023-07-06 at 20 57 59" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/cc712f79-bcf8-4869-a578-1060b8d42d86">
And using [this trick](https://css-tricks.com/snippets/html/mailto-links/) to make your link follow to mail app

2023-07-07 09:51 UTC, volodymyr-soltys97 requested changes
Still not fixed from previous review
<img width="238" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/2515fbfd-3b93-44c3-a2ec-4086fbf64434">

2023-07-07 18:19 UTC, anastasiiavorobiova approved these changes
Awesome!

2025-08-04 16:11 UTC, closed without merging