the met
mate-academy/layout_landing-page pull request #238
Opened 2023-06-26 22:53 UTC by VladyslavKolisnyk

DEMO LINK https://vladyslavkolisnyk.github.io/layout_landing-page

2023-06-27 09:56 UTC, volodymyr-soltys97 requested changes
Good work 👍 
Let's to fix some moments
Add transition and cursor: pointer for all clickable elements when on hover
<img width="386" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/6f6b5139-5a05-4c22-9e44-d73800651e45">
<img width="502" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/4f4498ca-d84c-4f16-ac03-0bb09dc201f3">

Need to remove default styles after autocomplete
<img width="520" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/25b3469a-81f1-4391-8f56-c79d289e0856">

2023-06-27 15:48 UTC, loralevitska requested changes
Good job! There are things that should be fixed:

- still don't fixed 
![image](https://github.com/mate-academy/layout_landing-page/assets/70009205/048eb3bd-d43c-4867-93b7-f2d66a181da9)
- disable text-area resize, it breaks design
![image](https://github.com/mate-academy/layout_landing-page/assets/70009205/bc35d650-3716-4900-8353-a24796dc948d)
- also add cursor pointer to all interactive elements

2023-06-28 09:15 UTC, volodymyr-soltys97 requested changes
Check indents on mobile version
<img width="545" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/b6dd99a8-750c-40bb-b0ef-0cda060568d0">

Add additional styles for these elements when hovering
<img width="512" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/e5a34275-4b77-4481-9487-a3669af0f8f6">

2023-06-28 15:11 UTC, anastasiiavorobiova requested changes
Really nice looking landing! Let's make it perfect

2023-06-28 15:11 UTC, anastasiiavorobiova commented on src/index.html
Check the validity of your HTML with [HTML validator](https://validator.w3.org/nu/#textarea)

2023-06-29 05:52 UTC, anastasiiavorobiova approved these changes
Awesome!

2023-12-02 10:32 UTC, closed without merging