landing-page-mobile
mate-academy/layout_landing-page pull request #26
Opened 2023-05-30 15:36 UTC by DmitryVolchokFE

https://DmitryVolchokFE.github.io/layout_landing/](https://dmitryvolchokfe.github.io/layout_landing-page

2023-05-31 07:15 UTC, OleziO requested changes
![image](https://github.com/mate-academy/layout_landing-page/assets/56752562/c6eb4e97-7fc7-46fd-b9e5-492b37bf0dc5)
Fix demo

2023-05-31 07:16 UTC, OleziO requested changes
.

2023-05-31 07:40 UTC, DmitryVolchokFE commented
soorry, new link (https://dmitryvolchokfe.github.io/layout_landing-page)

2023-05-31 11:58 UTC, demetrxx requested changes
Size and position of many images don't match design at all. 
Hero img isn't centered. 
Compare bikes list items items should be in one row.
Contact us section layout doesn't match the design
Footer has wrong height.

Please review your layout and make sure it, at least, looks like in the provided design. 
Waiting for your fixes.

2023-06-03 09:21 UTC, DmitryVolchokFE commented
Good afternoon, I submit this page for verification, in the task: https://mate.academy/learn/css-advanced/bem?section=video&videoId=4559&testTaskSlug=markup_landing_page
At the end of the lesson, it was indicated to create a mobile page, and to adapt the menu and header to the tablet. I did it. There is no adaptation for PC. (https://dmitryvolchokfe.github.io/layout_landing-page)

2023-06-03 16:56 UTC, anastasiiavorobiova requested changes
Great work!
See comments to improve it a bit.

2023-06-03 16:56 UTC, anastasiiavorobiova commented on src/index.html
> +            <a href="#menu" class="icon__position icon--menu"></a>
Consider using the aria-label attribute to explain the purpose of this empty link. It has a significant impact on accessibility of this page.

2023-06-03 16:56 UTC, anastasiiavorobiova commented on src/index.html
> +          <a href="#" class="icon__position icon--close"></a>
Consider using the aria-label attribute to explain the purpose of this empty link. It has a significant impact on the accessibility of this page.

2023-06-03 16:56 UTC, anastasiiavorobiova commented on src/styles/blocks/contacts.scss
> +    color: #bbb;
Consider using variables for this

2023-06-08 06:44 UTC, Volodymyr-Melnyk-Fron10der requested changes
1. ![image](https://github.com/mate-academy/layout_landing-page/assets/122989585/2ab185cb-6f67-4cfb-b1f8-89593dd55616)

2. add favicon 
![image](https://github.com/mate-academy/layout_landing-page/assets/122989585/68263044-b896-4dff-ace7-b8eacd4b301c)

3. fix button width 
![image](https://github.com/mate-academy/layout_landing-page/assets/122989585/9e098b21-c354-4470-bc8a-6e57ede5aaa4)

4. all images should be scaled on the hover 
![image](https://github.com/mate-academy/layout_landing-page/assets/122989585/8326f641-bd15-41fc-a8f7-a707b4b5661c)

2023-06-09 11:23 UTC, nazarmatsevych requested changes
1. images should not overlap each other
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/17df0cc4-e614-445d-ab36-e941f95f70df)


2. Page should not reloads or lead to 405 page on submit, also clear form fields on button click
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/5f8907e4-dade-4261-bdcd-5b9a2f3a5e4a)

If you have any questions - feel free to ask them in fe_chat

2023-06-09 12:22 UTC, volodymyr-soltys97 requested changes
Add transition for this button when on hover and remove default borders for this element
<img width="661" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/8f61e2c7-1294-4018-99a2-91249ad815b2">
<img width="463" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/15f4a110-6349-4e81-85ae-bbac1e3cceb4">
Fix this problem when on hover
<img width="284" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/4f21d865-40f8-4466-842e-d9de330e98c0">

2023-06-09 13:14 UTC, DmitryVolchokFE commented
Recorded all comments

2023-06-09 13:52 UTC, volodymyr-soltys97 requested changes
Not everything has been fixed since the last review, check the comments and fix them

2023-06-09 14:16 UTC, DmitryVolchokFE commented
Then I did not fully understand what was meant, corrected.

2023-06-10 07:01 UTC, Volodymyr-Melnyk-Fron10der approved these changes

2023-11-15 11:14 UTC, closed without merging