solution
mate-academy/layout_landing-page pull request #293
Opened 2023-07-08 12:40 UTC by Igor-Yaremchuk

[DEMO LINK](https://Igor-Yaremchuk.github.io/layout_landing-page/)

2023-07-08 16:54 UTC, lerastarynets requested changes
Pls watch the video review :)

https://github.com/mate-academy/layout_landing-page/assets/77551820/8d001964-cd7c-42d5-a9ec-c1f3b6bebd33

2023-07-10 10:41 UTC, Anastasiia-Svintsova requested changes
Almost done! Let's fix some design mismatches 

- Increase the space between the logo and menu items 
![image](https://github.com/mate-academy/layout_landing-page/assets/99403198/94ac4637-8d79-402e-bade-1c254edd58ce)

- Remove this space 
![image](https://github.com/mate-academy/layout_landing-page/assets/99403198/bba26be5-06a7-4c57-9dde-038b247beaf4)

- This section doesn't match the design on small screens 
![image](https://github.com/mate-academy/layout_landing-page/assets/99403198/72fe36e1-eba6-4c2e-a0a5-7241aa310360)

2023-07-11 13:38 UTC, witflash requested changes
Great job!
I see you've fixed most of the problems.
The last thing I see you could improve:
- remove scroll on the menu open

![image](https://github.com/mate-academy/layout_landing-page/assets/25587299/85d12c26-4f86-45df-8704-4a52cb1226b7)

You can use a little bit of JS to handle this.

2023-07-17 06:50 UTC, polosanya requested changes
Almost perfect!
1. Phone number and icon should be clickable with ability to call
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/897669f8-e59d-4a7e-a19a-c5b1cb32a7ba)
2. Make sure that all interactive elements have a cursor pointer on hover
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/c546f2f7-c392-483b-b997-62e730622dcf)
3. Section doesn't match the design on tablets
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/0999869c-8c95-4d1d-b463-1b027cf2c18f)
![image](https://github.com/mate-academy/layout_landing-page/assets/96409563/d8e2ea28-2e45-4208-9aed-73fa805ed70b)

2023-07-17 16:49 UTC, lerastarynets approved these changes
You've got this, keep pushing forward!

2025-03-23 12:55 UTC, closed without merging