add landing mybike
mate-academy/layout_landing-page pull request #344
Opened 2023-07-19 10:15 UTC by Vladyslav-amp

[DEMO LINK](https://Vladyslav-amp.github.io/layout_landing-page/)

2023-07-19 11:09 UTC, volodymyr-soltys97 requested changes
Good start 👍 
Let's improve your page
1. Need to fix header on desktop version
<img width="389" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/9e362a70-37d0-4c80-926e-ac6b24f0d208">

2. Add favicon on page
<img width="127" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/90d7a972-6365-4ec1-97e5-f673eeaf9d1c">

3. Need to remove scroll when this menu is open
<img width="1508" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/fd854f3a-841e-44fb-8e70-c54d831b6711">

2023-07-28 06:38 UTC, vlad-demchuk requested changes
1. there should be clickable hover effect for call icon

<img width="255" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/4205935e-84a3-4934-8ba1-fdad1dd0970d">
2. 

<img width="541" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/02165325-d6dd-4ef2-ad84-5d08f5b7ba13">

3. scroll isn't disabled

<img width="1130" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/c654ed56-c294-4a22-8fb0-e1e15dab9ef4">
4. the button width doesn't match the design

<img width="1092" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/612cfadf-fc68-47bc-b117-f8005183629c">
5. contact us doesn't match the design

<img width="943" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/750ef26d-50cc-4db4-bd2f-58243ed16c35">
design 

<img width="655" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/46dd288e-eebc-40af-b7de-e27d908a346d">

6. you have spaces in textarea

<img width="357" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/b0a7a2ac-3af8-425f-b3bd-8beb0e8bdd7a">

7. all form fields should be required and cleared on form submission
8. phone link leads to 404, address should be a link as well

<img width="255" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/102411130/fa2dda35-b898-4331-b973-6d073733c45d">

2023-08-06 13:46 UTC, anastasiiavorobiova requested changes
Great work! Consider fixing validation errors: 
<img width="1125" alt="Screenshot 2023-08-06 at 16 40 14" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/717c83c5-5443-4acd-98aa-d860848ff6c4">
<img width="824" alt="Screenshot 2023-08-06 at 16 39 23" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/befa1dc8-5d85-492f-a13e-0d86eadb8cf4">
Consider forbidding the page to scroll and make the menu scrollable for the landscape mode.  
<img width="708" alt="Screenshot 2023-08-06 at 16 38 41" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/ed296475-52e2-4e1c-9293-2b8386b52ba0">
The background-position for mobiles doesn't match the Figma design
<img width="580" alt="Screenshot 2023-08-06 at 16 38 33" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/04b771af-823d-477a-91cf-046dde6e0ba3">
Check indentations here
<img width="578" alt="Screenshot 2023-08-06 at 16 38 19" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/f3382dd6-d176-40eb-becf-2394a7a3291e">
The background position for the desktop doesn't match the Figma design. 
<img width="208" alt="Screenshot 2023-08-06 at 16 38 01" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/ced7603e-7a80-4b9c-87aa-4a8dc76aa37b">
Consider making the link follow google maps 
<img width="371" alt="Screenshot 2023-08-06 at 16 37 41" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/fa0ba50d-c543-400b-b612-c1f6e869c455">
Consider removing outlines 
<img width="234" alt="Screenshot 2023-08-06 at 16 37 33" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/fdf6202b-ebdc-48bb-b5ad-ef6e989f2426">
This link doesn't work 
<img width="699" alt="Screenshot 2023-08-06 at 16 37 22" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/0faad9b8-6d96-4f77-bd4b-e5e59431aeaa">
<img width="559" alt="Screenshot 2023-08-06 at 16 37 15" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/4da984c3-6952-4a1e-9f72-ac0933a7cf28">
The form should be cleared after submission. 
<img width="216" alt="Screenshot 2023-08-06 at 16 36 40" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/3a18bf03-46d1-427a-b424-3ec95a7a46b0">
Consider hacking text styling for the textarea
<img width="538" alt="Screenshot 2023-08-06 at 16 36 33" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/040302b9-52d0-49a9-a43f-e95f41e48eb8">
Consider adding a hover for this button

2023-08-11 16:46 UTC, Vladyslav-amp commented
In my last commit I can't remove scroll in burger menu. Only imgs from categories scroll. I tried to fix it in many ways and it still not working. Can you give me a hint to fix it?

2023-08-12 10:19 UTC, volodymyr-soltys97 requested changes
Information on how to remove scrolling is available in the task checklist.
https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md

2023-08-13 13:13 UTC, volodymyr-soltys97 requested changes
1. Add hover effects for these clickable elements
<img width="275" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/647630b5-60b5-46a8-a0b8-d1eeba75b812">

2. The user will not be able to stretch this window
<img width="1508" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/279ac100-3824-474b-a837-6c70bb3e1450">

3.  Need to fix the background image in footer
Demo
<img width="1511" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/b37536c2-f6ff-49fe-a883-e0f5714e450f">

Design
<img width="806" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/0880f2a5-06f9-4174-934f-efbd4446111e">

2023-08-13 15:54 UTC, anastasiiavorobiova requested changes
Great work! Almost perfect: <img width="637" alt="Screenshot 2023-08-13 at 18 51 14" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/11d6bb1e-616e-4cba-89b5-a6960a6c1e0f">
1) Consider fixing validation errors 
<img width="878" alt="Screenshot 2023-08-13 at 18 47 54" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/7664b9a9-80cf-465b-9c33-495498f12405">
2) Add menu scroll for landscape mode
<img width="237" alt="Screenshot 2023-08-13 at 18 46 34" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/ddfe99ef-4b20-43d1-b71b-3ed741d93b45">
3) Check font styles here
<img width="341" alt="Screenshot 2023-08-13 at 18 46 26" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/e6626225-dd3f-4e05-a555-069683c99a95">
4) Consider fixing the background for autocomplete

2023-08-13 15:54 UTC, anastasiiavorobiova commented on src/index.html
> +                <img src="images/MyBike-white.svg"
```suggestion
                <img 
                  src="images/MyBike-white.svg"
```
Consider fixing indentations accordingly to the code style guide

2023-08-13 15:54 UTC, anastasiiavorobiova commented on src/index.html
> +                <a href="tel:+123455555555"
See my previous comment

2023-08-14 06:31 UTC, volodymyr-soltys97 requested changes
1. When I move the cursor over these fields, they jump a little, this needs to be fixed
<img width="560" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/48a2a525-e1b3-4670-8219-0045995785ae">

2. Add transition for hover effects
<img width="421" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/ec7546be-e04d-4e25-a418-cd2debadb81d">
<img width="516" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/22006da3-289b-4e3d-9b9b-1a178191f439">

3. Need to fix position image on the mobile version
Demo
<img width="519" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/c6d2c127-40a0-4e4e-ad39-96c4e94b7f72">

Design
<img width="354" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/25bccbc9-08a0-4b5f-8bcc-5dc3e96bcb05">

4. The same as above
Demo
<img width="574" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/fda8232b-7be2-4cda-96f1-41349b4687a9">

Design 
<img width="716" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/020fc9d9-47f1-4e3f-a4c9-3238fe9665a7">

2023-08-16 07:24 UTC, Vladyslav-amp commented
1. I tried to fix problem when moved cursor on input and it jump, nothing not help(
2. My header background for tablet mode doesn't fit, problem with width, its problem with original size of image or its my mistake? (added   background-size: cover ) img is too wide for tablet mode. 
3.  Footer problem the same like in header, for landscape mode img fit with all width, but when I tried to change size for tablet or phone, the image is too wide. I tried to write background-size: contain - that help, but I had vertical white space. 
Could you give me a hint or point out my mistake to me.

2023-08-16 08:10 UTC, volodymyr-soltys97 requested changes
1. Need to remove border for hover effects for these fields
2. You can use background-position with percent

2023-08-16 10:46 UTC, volodymyr-soltys97 requested changes
Need to fix the burger menu, check it on the design
<img width="1104" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/927a3486-7f28-4eb4-8543-007cbe4228ad">

2023-08-16 12:27 UTC, anastasiiavorobiova approved these changes
Fantastic work! Looks awesome!

2024-01-25 15:50 UTC, closed without merging