Develop
mate-academy/layout_landing-page pull request #441
Opened 2023-08-01 16:47 UTC by mishakoshilka

- Deploy and create a Pull Request with a [DEMO LINK](https://mishakoshilka.github.io/layout_landing-page/)

2023-08-01 16:47 UTC, mishakoshilka commented
[DEMO LINK](https://mishakoshilka.github.io/layout_landing-page/)

2023-08-01 17:08 UTC, loralevitska requested changes
A little more and you will be on target)

- add phone number by phone icon hover
![image](https://github.com/mate-academy/layout_landing-page/assets/70009205/379dabc8-58e1-447c-92d2-941999e530cc)
- make sure that all interactive elements have a cursor pointer on hover
- remove default autocomplete background color, it breaks design 
![image](https://github.com/mate-academy/layout_landing-page/assets/70009205/f707d388-eca5-495d-afae-347945cac650)
- fix form submit it doesn't work now

2023-08-03 13:52 UTC, anastasiiavorobiova requested changes
Great work! Consider fixing validation errors: 
<img width="1127" alt="Screenshot 2023-08-03 at 16 50 02" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/686d698a-6f98-47e5-91d6-73ab8375abf6">
<img width="1423" alt="Screenshot 2023-08-03 at 16 50 17" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/2f75337a-c3e9-47e9-8102-3cda7ee95bd0">
<img width="1384" alt="Screenshot 2023-08-03 at 16 50 23" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/7382b0f5-ca54-42c3-b9ad-0f35d42f1c1b">
<img width="826" alt="Screenshot 2023-08-03 at 16 49 29" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/9b483c5d-e343-4174-9b15-3c9cdee621c1">
The menu in landscape mode should be scrollable
<img width="1096" alt="Screenshot 2023-08-03 at 16 48 28" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/926907f3-4451-4435-9eed-abd237299942">
There is a visible background, consider fixing it

2023-08-04 07:01 UTC, volodymyr-soltys97 requested changes
1. Make all these fields are required
<img width="572" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/6c25d95f-487f-4e87-9191-3ba9d8ddaf1d">

2. When I click send I get this error
<img width="979" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/3f4f21d3-5044-4ff1-9d95-46b5cd76e8ca">

3. Add transition for hover effects for these elements
<img width="320" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/895e60dd-adeb-47d4-8233-53982a04fe38">

2023-08-04 08:20 UTC, volodymyr-soltys97 requested changes
1. Still not fixed from the previous review
<img width="474" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/fde41090-5fb6-46ea-bc33-b056dc538b72">

2. When I click send page should not scroll on top page/
<img width="484" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/f4ef5fa8-58b6-4d18-add5-0c892e33a766">

3. Also, data from the form does not need to be shown in the URL address
<img width="759" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/51d65da8-a1c5-42bc-90d2-d69fc53b238c">

2023-08-04 09:25 UTC, volodymyr-soltys97 requested changes
The background of these fields is different, also when I click on send there is no information that the field is mandatory
<img width="619" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/6a8409b4-ec2e-4081-8903-797847259410">

2023-08-07 10:06 UTC, volodymyr-soltys97 requested changes
Almost done!
Let's improve code style

2023-08-07 10:06 UTC, volodymyr-soltys97 commented on src/index.html
> +                <a href="tel:+1-234-5555-55-55" class="icon icon--phone"></a>
Need to fix format phone everywhere only in href
```suggestion
                <a href="tel:+123455555555" class="icon icon--phone"></a>
```

2023-08-07 10:06 UTC, volodymyr-soltys97 commented on src/index.html
> +            class="top-bar__logo">
Need to check and fix it everywhere
```suggestion
            <img
              src="images/logo.png"
              alt="Logo Nothing"
              class="top-bar__logo"
            >
```

2023-08-07 11:35 UTC, volodymyr-soltys97 approved these changes
Well done 🔥

2024-12-27 08:59 UTC, closed without merging