Landing page BIKE
mate-academy/layout_landing-page pull request #445
Opened 2023-08-02 17:54 UTC by BodyaKutsyk

-[preview link](https://bodyakutsyk.github.io/layout_landing-page/)
-[website layout](https://www.figma.com/file/NZQAIydtHo5QkINyGLHNcq/BIKE-New-Version?node-id=0%3A1)

2023-08-02 18:30 UTC, TarasHoliuk commented
1. Add transition to all elements (directly to an element) that have a hover effect
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/503682fa-8794-43ba-8189-6c3cd0f09c28)

2. The button shouldn't be full-width on the desktop version:
mockup:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/0c11f6de-0e6c-473f-b626-cf5118ee3907)
app:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/46572182-752e-4fa8-b7dd-c67048d1e0c9)

3. Make the logo color in the menu the same as in the mockup (black): 
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/2575563a-15c1-46c4-baa2-fde4a524d8b5)

4. Use the image w/o the label at the bottom:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/83b2d4e3-a959-4311-aaea-ea119b73161e)
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/0ef221bb-8a0a-49f7-aaef-c128842c5f49)

5. I'd increase max-width a bit for big screens (FullHd resolution example)/use relative units:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/ad31c71a-d8f3-45d0-8b40-2a661c54e17e)
I know there is no design for such a resolution, but you will add it to the portfolio, so would be nice to handle it (if some recruiter opens it on the laptop)

2023-08-02 18:30 UTC, TarasHoliuk requested changes
You did an amazing job :+1: 
lat's improve it a bit

2023-08-03 06:59 UTC, volodymyr-soltys97 requested changes
1. Need to fix background-image in footer
Demo
<img width="1512" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/d24c72b0-3420-49a6-952e-be82a28a7e9c">

Design
<img width="969" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/ec73ce89-feef-4857-bc5b-a7a6919e49bc">

2023-08-03 06:59 UTC, volodymyr-soltys97 commented on src/index.html
> +              <a href="tel:+1 234 5555-55-55" class="icon icon--phone"></a>
Need to fix format phone only in href
```suggestion
              <a href="tel:+123455555555" class="icon icon--phone"></a>
```

2023-08-03 06:59 UTC, volodymyr-soltys97 commented on src/index.html
> +                href="favicon.ico?"
Do you need `?` here?
```suggestion
                href="favicon.ico"
```

2023-08-03 06:59 UTC, volodymyr-soltys97 commented on src/index.html
> +          <a href="tel:+1 234 5555-55-55" class="menu__phone-number">
The same as above

2023-08-03 06:59 UTC, volodymyr-soltys97 commented on src/index.html
> +            ">
```suggestion
            <h2
              class="
                about-us__title
                section-title
                section-title--align--left"
            >
```

2023-08-03 06:59 UTC, volodymyr-soltys97 commented on src/index.html
> +                </p>
```suggestion
                <p class="section__category">
                  Brakes with total stopping power the
                  second you make contact. The
                  removable battery has up to 70km
                  battery autonomy and weighs only 2.4
                  kg. Lights integrated into the frame
                  give you always-on visibility day and
                  night.
                </p>
```

2023-08-03 06:59 UTC, volodymyr-soltys97 commented on src/index.html
> +                  <a class="contact-info__data" href="tel: +1 234 5555-55-55">+1 234 5555-55-55</a>
The same as above

2023-08-03 10:51 UTC, volodymyr-soltys97 requested changes
The user will not be able to change the size of the field
<img width="1510" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/3384f909-35d8-4b7c-a3f6-df57fe74b358">

2023-08-03 12:49 UTC, IvanFesenko requested changes
Images overlapping menu - to fix increase z-index for menu
![2023-08-03_15h45_17](https://github.com/mate-academy/layout_landing-page/assets/61904995/57e4b2cc-ca70-422c-aff4-f6504951622b)

Images overlapping each other
https://github.com/mate-academy/layout_landing-page/assets/61904995/36c360ed-9577-4318-820b-bbc9d834fe5b

Design missmatch
AR:
![2023-08-03_15h48_33](https://github.com/mate-academy/layout_landing-page/assets/61904995/1cca2156-6f58-455c-9068-a2f37e18b899)

ER:
![2023-08-03_15h48_27](https://github.com/mate-academy/layout_landing-page/assets/61904995/f8ab3780-e75c-45ce-be4e-dedfce962adf)

2023-08-03 16:29 UTC, TarasHoliuk commented
Fix font-weight:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/d4f05bab-d6ef-4cb7-87f4-a3fe8b5f2434)
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/6216db89-4c9d-492b-bdd9-6f1f889bac79)

2023-08-03 16:29 UTC, TarasHoliuk requested changes
Almost perfect :+1: 
Let's add one more fix

2023-08-03 18:22 UTC, polosanya approved these changes
Well done! 🔥

2025-10-01 17:47 UTC, closed without merging