Landing
mate-academy/layout_landing-page pull request #567
Opened 2023-09-12 10:02 UTC by yulabakun

- [DEMO LINK](https://yulabakun.github.io/layout_landing-page/)

2023-09-12 17:49 UTC, Helen-arch requested changes
Great job! just a few suggestions

2023-09-12 17:49 UTC, Helen-arch commented on src/index.html
> +                  <img
better leave one empty line between multilines childs

2023-09-12 17:49 UTC, Helen-arch commented on src/index.html
> +                  The removable battery has up to 70km battery autonomy and weighs only 2.4 kg. Lights integrated into the frame give you always-on visibility day and night.
better make the line length < 80 with keyboard enter

2023-09-12 17:49 UTC, Helen-arch commented on src/index.html
> +            <p class="about-us-text">
better set that as __element

2023-09-13 19:27 UTC, Oleksandr-kopaevich requested changes
Hi @yulabakun, nice work, but it seems not finished. Let's fix all the points and make it flawless.
7. Increase all images on hover (make them links to #, if there is no better option)
-- You are not using images like links, please fix this
9. The speed of animations should be the same throughout the page (for example, increasing when hovering or moving blocks when scrolling)
-- you don't have transitions, add it
16. Make footer sticky at the bottom with z-index: -1 to get fixed background effect.
-- it's still not sticky, use position: sticky + other related css properties.
And please see some comments on the screenshots from the demo
![image](https://github.com/mate-academy/layout_landing-page/assets/45945732/24f809f2-fbde-4a8c-b0d2-cfade5a6a558)
![image](https://github.com/mate-academy/layout_landing-page/assets/45945732/749c192a-ad7f-4fa6-b489-3bf7ef6e41f3)
![image](https://github.com/mate-academy/layout_landing-page/assets/45945732/4596459d-5a24-4668-9033-19db3f422634)
![image](https://github.com/mate-academy/layout_landing-page/assets/45945732/840327b5-40c4-48a1-b9bc-b4117bf03cc5)

2023-09-13 20:05 UTC, Oleksandr-kopaevich requested changes

2023-09-13 20:05 UTC, Oleksandr-kopaevich commented on src/styles/blocks/contacts.scss
> +    font-family: "Poppins", Arial, sans-serif;
The same with font-size and font colors

2023-09-14 11:12 UTC, yulabakun commented on src/styles/blocks/top-bar.scss
> +    position: relative;
I use it to position pseudoelement  ::before which appears on a desktop while hovering over a phone icon in icon.scss (lines 17-24)

     @include onDesktop {
      &::before {
        content: "+1 234 555-55-55";
        color: #fff;
        display: none;
        position: absolute;
        top: 20%;
        left: -500%;
      }

      &:hover::before {
        display: inline;
      }
    }

2023-09-14 14:15 UTC, StasSokolov approved these changes
Good job, i'm approving it, only few minor comment from me!

Check please in future image quality
![Снимок экрана 2023-09-14 в 17 14 18](https://github.com/mate-academy/layout_landing-page/assets/75898310/38d5d370-5fb2-4a4a-b74f-5d23db9ea0d8)

2023-09-14 14:15 UTC, StasSokolov commented on src/styles/blocks/header.scss
> +  background-position: center;
don't repeat yourself, move this code to `mixins` and reuse them

2025-02-13 12:41 UTC, closed without merging