Develop
mate-academy/layout_landing-page pull request #57
Opened 2023-06-04 07:25 UTC by OleksiiSym

[DEMO LINK]https://OleksiiSym.github.io/layout_landing/

2023-06-04 10:08 UTC, Volodymyr-Melnyk-Fron10der requested changes
1. don't see your solution
![image](https://github.com/mate-academy/layout_landing-page/assets/122989585/206de52f-871f-4569-a45d-da7651ffabbb)

2023-06-04 13:23 UTC, OleksiiSym commented
Sorry for that, edited already

2023-06-04 13:23 UTC, OleksiiSym commented
> 

Sorry for that, edited already

2023-06-04 13:46 UTC, volodymyr-soltys97 requested changes
Good start 👍 
Let's to fix some moments
Call number don't working. Also add a phone number when on hover to call
<img width="114" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/3859ca47-0384-4f54-9d79-1f3b36459f08">
Also add transition when this menu appears at page
<img width="1481" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/6f9e04d7-7e97-40eb-a21f-0474b5787982">

2023-06-04 17:34 UTC, OleksiiSym commented
> Good start 👍 Let's to fix some moments Call number don't working. Also add a phone number when on hover to call <img alt="image" width="114" src="https://user-images.githubusercontent.com/64750958/243181771-3859ca47-0384-4f54-9d79-1f3b36459f08.png"> Also add transition when this menu appears at page <img alt="image" width="1481" src="https://user-images.githubusercontent.com/64750958/243181849-6f9e04d7-7e97-40eb-a21f-0474b5787982.png">

Thanks, fixed issue with phone icon but dont know how to make transition for menu appearance. May you give some advice?

2023-06-05 07:23 UTC, vlad-demchuk commented
if you use `transfom` for menu, just add `transition: transform 0.3s` for the element  for example
feel free to ask your question it in fe_chat

2023-06-05 08:54 UTC, closed without merging

2023-06-05 09:45 UTC, nazarmatsevych requested changes
Good work!
Just add hover effects to all interactive elements
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/ad3d6471-586a-41e6-9f8a-d21b1b699d29)
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/67c5e180-9abc-4cd2-b5b3-43b7ce6f2ff0)

2023-07-10 11:37 UTC, volodymyr-soltys97 requested changes
Let's improve your page
1. Add favicon to page
<img width="148" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/1f2a8a3b-d7e3-4bd1-8016-3d1fcb2553cd">

2. Need to show phone number when hovering this icon
<img width="105" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/fa84baa8-af2b-442d-9e55-c2834a0f9c4d">

3. Need to remove scroll when this menu is open
<img width="1510" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/771f91cb-3542-4be2-ac27-211cce07773a">

2023-08-04 06:59 UTC, volodymyr-soltys97 requested changes
1. Add placeholder text for all input
<img width="779" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/a7b2dfad-e9ac-4fb2-806d-fc08178af1bb">

2. Add hover effects for all clickable elements
<img width="266" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/19f3d4c3-07ad-4793-8fff-63bc10d92315">

3. Add `cursor: pointer` and transition for this button
<img width="736" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/941df980-c606-4e5b-8ef3-cf54e1c2825b">

4. Need to make all these fields are required
<img width="734" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/f83b7a4a-179d-4636-b6b9-379d706a2ed9">

5. I get this error after send form
<img width="414" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/c66a7a5c-5217-40f2-acd1-84d857d4b8eb">

2023-08-05 10:44 UTC, TarasHoliuk commented
Checklist 6:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/d06e4686-2e89-45a7-a5d7-2160a7627372)

Checklist 7:
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/f8f1a4b3-1d8f-431d-8f35-2cea592f82a8)

2023-08-05 10:45 UTC, TarasHoliuk requested changes
GJ :+1: 
Almost done - carefully read the checklist and ensure you achieved all goals

2023-08-05 10:45 UTC, TarasHoliuk commented on src/index.html
> +      <section class="contact conteiner">
```suggestion
      <section class="contact container">
```
typo

2023-08-05 10:45 UTC, TarasHoliuk commented on src/index.html
> +        <form
have you tried it (the [checklist](https://github.com/mate-academy/layout_landing-page/blob/main/checklist.md))?
![image](https://github.com/mate-academy/layout_landing-page/assets/86923089/823f7e7a-0640-4882-8bb8-ac76186482ae)

2023-08-06 12:30 UTC, anastasiiavorobiova requested changes
Great work! Almost done! Consider fixing validation errors (mostly it's mistyping of tag names): 
<img width="980" alt="Screenshot 2023-08-06 at 15 25 53" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/6b3bc788-5b01-4cb7-b0f2-3764dc6f3745">
<img width="1112" alt="Screenshot 2023-08-06 at 15 26 04" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/37f3ff4e-858d-4e2d-9249-059cb1e0eec3">
<img width="1161" alt="Screenshot 2023-08-06 at 15 27 36" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/6c4bfe65-8780-4f22-8639-e99ba1795445">
<img width="441" alt="Screenshot 2023-08-06 at 15 23 41" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/32a62d15-6d59-43af-902e-3fff1725673f">
Check margins between products.
<img width="329" alt="Screenshot 2023-08-06 at 15 21 44" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/89a60913-d85b-4914-be86-ff6e765f55d4">
These links should be anchor links. Consider also adding transitions for hovers

2023-08-07 08:16 UTC, volodymyr-soltys97 requested changes
1. Need to change autocomplete styles for input
<img width="828" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/f1e5511b-e2fd-4aed-af60-e5399dc40b03">

2. Add transition for hover effects here
<img width="796" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/34b3edc1-795d-47fd-b816-fbb1326a1bdb">

2023-08-20 13:56 UTC, anastasiiavorobiova approved these changes
Looks outstanding!