add task solution
mate-academy/layout_landing-page pull request #602
Opened 2023-09-13 22:19 UTC by LadyLiza

[DEMO LINK](https://ladyliza.github.io/layout_landing-page/)

2023-09-14 06:52 UTC, etojeDenys requested changes
1. let's disable textarea scaling
<img width="1183" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/70220667/6e7a90f9-4303-43ea-8a2c-93467583c81f">


2. number should appear on hover
<img width="299" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/70220667/2427b169-25de-4e1f-ad02-0fed1cb34c85">


3. Use landing name as a page title

2023-09-15 06:23 UTC, volodymyr-soltys97 requested changes
1. Add transition for hover effects everywhere
<img width="433" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/f0e3dd48-3bbc-4d18-81ff-682b3fb4a826">

2. Add placeholder text here
<img width="584" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/178e99ba-a452-4990-830a-bd654dc1c8f9">

3. Need to fix the indents for the last field
<img width="535" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/25a2de5a-cdf1-42fb-aa39-49367cc3db83">

2023-09-15 08:41 UTC, volodymyr-soltys97 requested changes
1. Add transition for hover effects for these elements
<img width="284" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/dc7a40bc-2fd0-4a1f-a564-a6b64db01852">

2. Need to hide the phone number on the mobile version
<img width="213" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/cb5d6ace-5bb4-47b4-937f-be04b7c09b0e">

2023-09-15 08:48 UTC, LadyLiza commented
I apologize, I got confused and didn't do the necessary PR. I'll have it fixed within the hour.

2023-09-15 08:49 UTC, volodymyr-soltys97 requested changes
Still not fixed from the previous review, you need to make a deploy again

2023-09-15 09:14 UTC, OleziO approved these changes

2025-11-19 02:46 UTC, closed without merging