check intermediate result
mate-academy/layout_landing-page pull request #620
Opened 2023-09-20 16:23 UTC by mkovshun

2023-09-20 16:37 UTC, anastasiia-tilikina requested changes
please provide demo link

2023-09-26 12:54 UTC, mkovshun commented
https://mkovshun.github.io/layout_landing-page/

2023-09-26 13:28 UTC, anastasiiavorobiova requested changes
Great work! Added a few comments to fix https://www.loom.com/share/8b207ed6086e4615ab1ea5ed798cd16c

2023-09-26 13:28 UTC, anastasiiavorobiova commented on src/index.html
<img width="1109" alt="Screenshot 2023-09-26 at 16 10 58" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/cc81bcd2-ba96-4752-b380-68ec07cc9528">
Consider fixing validation errors

2023-10-02 17:47 UTC, mkovshun commented
https://mkovshun.github.io/layout_landing-page/

2023-10-02 17:51 UTC, etojeDenys requested changes
1. add some hovers to all links
2. make all fields in form required
3. click should start the call
<img width="231" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/70220667/1c1b8546-cfc6-495f-b256-5c1996a57e9d">

2023-10-02 18:04 UTC, mkovshun commented
im fix bug with quotes in aside

2023-10-02 18:34 UTC, plodnikate approved these changes
Yep! Super last final result this time! Really good job on it!

2023-10-02 18:37 UTC, closed without merging