Develop
mate-academy/layout_landing-page pull request #625
Opened 2023-09-22 11:45 UTC by AnoriFrell

[DEMO LINK] (https://AnoriFrell.github.io/layout_landing-page/)

2023-09-22 12:03 UTC, lerastarynets requested changes
Pls watch the video review :)

[link to video review](https://www.awesomescreenshot.com/video/20990581?key=6c2ffec170fdc5b4bb82957e941008b5)

2023-09-24 16:19 UTC, anastasiiavorobiova requested changes
Good work! Some additional comments to fix: 
<img width="808" alt="Screenshot 2023-09-24 at 19 17 07" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/acfa12dd-59d6-49a9-9a9d-c1e3ee46d05a">
The navigation overlaps the logo on the scroll
<img width="264" alt="Screenshot 2023-09-24 at 19 16 40" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/a1e2445d-d0d7-4b23-9576-f6579faed97c">
Consider removing the outline here
<img width="255" alt="Screenshot 2023-09-24 at 19 16 23" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/0cdd9a02-8f61-43be-88ef-a27d4a03d22e">
Should be clickable 
<img width="179" alt="Screenshot 2023-09-24 at 19 16 01" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/5c07cd7a-d0fa-478f-a719-202b8f62b68b">
<img width="104" alt="Screenshot 2023-09-24 at 19 16 06" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/c96bb6e2-3890-4030-aa17-276948faf2cb">
Check fonts here
<img width="168" alt="Screenshot 2023-09-24 at 19 15 46" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/b226b3db-b290-4953-af95-043d22572573">
<img width="240" alt="Screenshot 2023-09-24 at 19 15 51" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/f637abbe-643e-4c0a-8b15-32f2da0d64a9">
And here
<img width="1213" alt="Screenshot 2023-09-24 at 19 15 32" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/1146cff1-9929-496e-b62e-663a12e09eae">
<img width="785" alt="Screenshot 2023-09-24 at 19 15 36" src="https://github.com/mate-academy/layout_landing-page/assets/135232001/999af621-ceeb-4e2d-beef-3b7b9a932f55">
Don't meet the Figma design

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +              href="#" class="top-bar__logo-link">
```suggestion
              href="#" class="top-bar__logo-link"
            >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                  class="top-bar__logo cursor-main"
```suggestion
                src="images/Logo-2x.png"
                alt="MyBike logo"
                class="top-bar__logo cursor-main"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                >
```suggestion
              >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                class="product__photo">
```suggestion
                <img 
                  src="images/Sporty4.png"
                  alt="Sporty 4"
                  class="product__photo"
                >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                class="product__photo">
See my previous comment

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                class="product__photo">
The same issue here

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                    alt="Auto Unlock"
```suggestion
                      class="detail__photo"
                      src="images/AU1.png"
                      alt="Auto Unlock"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                    >
```suggestion
                      class="detail__photo"
                      src="images/AU2.png"
                      alt="Auto Unlock"
                    >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                    alt="Range & Integrated lights"
```suggestion
                      class="detail__photo"
                      src="images/R&I1.png"
                      alt="Range & Integrated lights"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                    alt="Range & Integrated lights"
```suggestion
                      class="detail__photo"
                      src="images/R&I2.png"
                      alt="Range & Integrated lights"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                    alt="Hydraulic disc brakes & Lightweight"
```suggestion
                      class="detail__photo"
                      src="images/H&L1.png"
                      alt="Hydraulic disc brakes & Lightweight"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                    alt="Hydraulic disc brakes & Lightweight"
```suggestion
                      class="detail__photo"
                      src="images/H&L2.png"
                      alt="Hydraulic disc brakes & Lightweight"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                class="button__link" href="#">
```suggestion
                <a class="button__link" href="#">
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +            class="contacts">
```suggestion
              onsubmit= "this.reset(); return false;"
              class="contacts"
            >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                >
```suggestion
              >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                >
```suggestion
              >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                  type="submit" class="button-send__style cursor-main"
```suggestion
                    type="submit" 
                    class="button-send__style cursor-main"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                href="tel: +1 234 5555-55-55" class="info__phone-number cursor-main"
```suggestion
                  href="tel: +1 234 5555-55-55" 
                  class="info__phone-number cursor-main"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                href="mail-to:hello@miami.com" class="info__email-address cursor-main"
```suggestion
                  href="mail-to:hello@miami.com" 
                  class="info__email-address cursor-main"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                class="info__address-data cursor-main"
```suggestion
                  href="https://maps.app.goo.gl/2MtKxyKeBPyRTtbi6"
                  target="_blank"
                  class="info__address-data cursor-main"
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +      src="images/footer.png" alt="Footer">
```suggestion
        class="footer__photo"
        src="images/footer.png" 
        alt="Footer"
      >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                <a class="nav__link cursor-menu" href="#">Home
```suggestion
                <a class="nav__link cursor-menu" href="#">
                  Home
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                <a class="nav__link cursor-menu" href="#about-us">About us
```suggestion
                <a class="nav__link cursor-menu" href="#about-us">
                  About us
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +                <a class="nav__link cursor-menu" href="#details">Details
```suggestion
                <a class="nav__link cursor-menu" href="#details">
                  Details
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +          <a href="tel:+1 234 5555-55-55"         class="menu__test-ride cursor-menu">
```suggestion
          <a href="tel:+1 234 5555-55-55" class="menu__test-ride cursor-menu">
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
Consider fixing validation errors

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +    href="https://fonts.googleapis.com">
```suggestion
    <link 
      rel="preconnect"
      href="https://fonts.googleapis.com"
    >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +    href="https://fonts.gstatic.com">
```suggestion
    <link 
      rel="preconnect"
      href="https://fonts.gstatic.com"
    >
```

2023-09-24 16:19 UTC, anastasiiavorobiova commented on src/index.html
> +    type="image/png" href="./images/favicon.png">
```suggestion
    <link 
      rel="shortcut icon"
      type="image/png" 
      href="./images/favicon.png"
    >
```

2025-01-12 15:52 UTC, closed without merging