Created first section for landing
mate-academy/layout_landing-page pull request #788
Opened 2023-11-12 18:24 UTC by OstTomash

- [DEMO_LINK](https://osttomash.github.io/layout_landing-page/)

2023-11-12 20:18 UTC, nazarmatsevych requested changes
Good start, keep going :)

2023-11-12 20:22 UTC, OstTomash commented
@nazarmatsevych 
Is there anything else I should add in this BEM task?
Because I see you suggested changes, but I don't see what.

2023-11-13 09:39 UTC, DarkMistyRoom requested changes
You will complete this landing step by step during the next blocks. Only when the whole page is complete we will approve this PR. 

So for now you've done a good job! Go ahead

And if you have any questions, please ask in the chat - you will get a response much faster

2023-11-18 08:12 UTC, sTorba24 requested changes
Well done! lets improve it

1. remove autocomplete styles for input(blue bg)
![image](https://github.com/mate-academy/layout_landing-page/assets/55200530/59d39206-7ac0-47c4-8935-ecdb0a7c3f2b)


2.add cursor pointer to all interactive elements(default cursor on buttons, check everywhere)
3. check background image on mobile version
![image](https://github.com/mate-academy/layout_landing-page/assets/55200530/5238ddb5-09ea-4030-bb01-3be1044653bf)


4.

2023-11-18 17:11 UTC, etojeDenys approved these changes
good job

2025-01-22 12:02 UTC, closed without merging