add task solution
mate-academy/layout_landing-page pull request #839
Opened 2023-11-29 03:14 UTC by MarkMatiushechko

- [DEMO LINK](https://MarkMatiushechko.github.io/layout_landing-page/)

2023-11-29 09:07 UTC, l4st1m0za requested changes
Great job! See the required changes. Also, it's better to use **.svg** instead of **.png** images. Continue working!

2023-11-29 09:07 UTC, l4st1m0za commented on src/styles/main.scss
> +}
It's better to use nesting as you have SCSS file which alows it. Try to implement it in all the possible places.

2023-11-29 09:07 UTC, l4st1m0za commented on src/styles/main.scss
> +  color: #1B2129;
It's better not to use single colour name, but to use constant which represents the colour.

2023-12-28 22:57 UTC, MarkMatiushechko commented
[DEMO LINK](https://MarkMatiushechko.github.io/layout_landing-page/)

2024-01-05 12:07 UTC, closed without merging