solution added (styles moved to main.scss)
mate-academy/layout_landing-page pull request #973
Opened 2024-01-10 20:30 UTC by happytravels38

[DEMO LINK](https://happytravels38.github.io/layout_landing-page/)

By video tutorial I have to to store styles in different files but terminal showed me an ERROR message (Unexpected extension ".scss" in @import) when I was trying to store links to the files in main.scss 

The requirement was (Start writing styles in the main.scss file. It is be explained in the Sass lesson)
so I added my styles to main.scss only

2024-01-11 08:41 UTC, volodymyr-soltys97 requested changes
Good start 👍 
Let's improve your code
1. Add the transition when this menu appears on the page, also need to remove the scroll when this menu is open
<img width="485" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/0e42a65d-16ea-4e3c-8c78-8e4959e9600f">

2. Add the favicon on the page
<img width="120" alt="image" src="https://github.com/mate-academy/layout_landing-page/assets/64750958/91677e56-ff25-4400-b703-f4f6ced198d2">

Keep going with other section

2024-03-19 17:01 UTC, nazarmatsevych requested changes
Good start, let's make some improvements

1. This field should be `<textarea>`
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/8c809977-1cc7-4ee9-9f19-b5d4b27f8b6f)

2. These links are not working
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/5e768b3c-e4d6-4aca-a16b-ad6b7c8fdd97)


3. Button should be inside your form and add cursor: pointer to it
![image](https://github.com/mate-academy/layout_landing-page/assets/80700247/d3384def-8f50-4164-8866-6d32fec33b17)

4. Tablet and desctop views were not implemented

2024-03-21 17:19 UTC, maxim2310 requested changes
Good work, but lets make some improvement 

1. these link don't working
![image](https://github.com/mate-academy/layout_landing-page/assets/96265844/9177ad93-de92-4703-87c6-63b646e61410)
2. it must be centered 
![image](https://github.com/mate-academy/layout_landing-page/assets/96265844/1fe5c92c-9a80-47d2-b4d9-40e8b7f974b5)
3. it must be aligned 
![image](https://github.com/mate-academy/layout_landing-page/assets/96265844/a21d50d7-c01d-4ab2-8b09-1cbfb44a2e86)
4. need remove autofill styles 
![image](https://github.com/mate-academy/layout_landing-page/assets/96265844/63060f38-f698-4383-8a84-ca4f80addc8f)
5. diferent font and strange padding 
![image](https://github.com/mate-academy/layout_landing-page/assets/96265844/d57f0469-5133-4b30-9d94-54cd06de5ca3)
6. after submit form page must not refreshing 
7. on desktop version need to check quality of img and add hover effects

2024-03-22 16:58 UTC, happytravels38 commented
I made adjustments except I do not understand - "4. need remove autofill styles" and 7 "and add hover effects". I made a hover effects, I do not understand what is wrong with it.

2024-03-22 17:35 UTC, vadiimvooo requested changes
Good job. A few fixes required:
1. Add hover effect for this links according to the mockup
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/98fd3da7-6497-465c-8d0e-9ba7cf492c75)
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/aa0e6aff-f712-47a9-b008-02ebf61b60cb)
2. This section is also should be centered as well as other ones
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/51b86558-dc2e-4b8c-b17b-41fba03c078a)
3. Wrong spacing between elements, please fix it.
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/6c17dd95-d4b7-4ba4-98b2-4abfada53271)
4. Add hover effect for the button, also provide cursor pointer as well
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/045d5883-8f31-4a6c-84b2-a374f730b152)
5. Remove the padding as it was mentioned above
![image](https://github.com/mate-academy/layout_landing-page/assets/108701488/66dcdbcb-9cb2-4efc-97aa-52b425208344)
6. On sending form you should reset form fields.

2024-05-09 05:27 UTC, etojeDenys approved these changes
lgtm

2025-06-16 18:31 UTC, closed without merging